[16기 홍연우] Add:상품 전체 보기, 페이징, 필터링
wecode-bootcamp-korea/Wepicker-backend pull request #4
Opened 2021-01-15 06:52 UTC by redsaumon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-15 08:11 UTC, redsaumon commented
@ulfrid 지훈님! 질문이 있습니다. 
1. 필터링 할 때 필터링마다 조건문을 만들어서 if문이 6개나 있는 게 좋아보이지 않는데 어떻게 개선할 수 있을까요? 
2. 제공하지 않는 필터가 요청될 경우 아무 if문에 걸리지 않고 for문으로 가버려서 UnboundLocalError: local variable 'products' referenced before assignment가 발생됩니다. UnboundLocalError로 오류처리를 했는데 이래도 되는 걸까요?

2021-01-15 09:04 UTC, ulfrid requested changes
수정 부탁드립니다!

2021-01-15 09:04 UTC, devops-andrew commented on product/views.py
> +            page_size    = 9
이 부분은 상수화 하는게 좋을것 같습니다.

2021-01-15 09:04 UTC, devops-andrew commented on product/views.py
> +            max_page     = math.ceil(Product.objects.all().count()/9)
```suggestion
            max_page     = math.ceil(Product.objects.all().count()/page_size)
```
이렇게 하면 하드코딩이 아니라 좋을것 같아요.

2021-01-15 09:04 UTC, devops-andrew commented on product/views.py
> +            max_page     = math.ceil(Product.objects.all().count()/9)
상수로 바꾸면 상수로 입력해주세요. (PAGE_SIZE)

2021-01-15 09:04 UTC, ulfrid commented on product/views.py
> +                products = Product.objects.order_by('-name').prefetch_related('image_url')[offset:limit]
```suggestion
            sort_type = {
            'min_price' : 'price',
            'max_price' : '-price',
            'abc'       : 'name',
            'descabc'   : '-name' 
            }
            if ordering is not None:
                products = Product.objects.order_by(sort_by[ordering]).prefetch_related('image_url')[offset:limit]
            else:
                products = Product.objects.order_by('pub_date').prefetch_related('image_url')[offset:limit]
            
            if ordering == 'best':
                products = Product.objects.annotate(Count('review')).order_by('-review__count').prefetch_related('image_url')[offset:limit]
            ```
이렇게 연속적인 if 로 낭비되는 코드는 줄여봅시다

2021-01-15 09:04 UTC, ulfrid commented on product/views.py
> +                product_list.append(product_dict)
```suggestion
            for product in products:
                image = product.image_url
                product_dict = {
                    'category'       : product.category.category,
                    'name'           : product.name,
                    'price'          : product.price,
                    'description'    : product.description,
                    'thumnail_image' : image.first().image_url,
                    'sub_image'      : image.all()[1].image_url,
                    'pub_date'       : product.pub_date
                }
                product_list.append(product_dict)
```
이코드는 리스트컴프리헨션으로 변경해 봅시다!!

2021-01-15 09:09 UTC, redsaumon commented on product/views.py
> +                products = Product.objects.order_by('-name').prefetch_related('image_url')[offset:limit]
지훈님 정리의 달인이시네요 멋져요

2021-01-15 09:09 UTC, redsaumon commented on product/views.py
> +                product_list.append(product_dict)
넵!!!

2021-01-15 09:10 UTC, redsaumon commented on product/views.py
> +            max_page     = math.ceil(Product.objects.all().count()/9)
네네!!

2021-01-15 13:20 UTC, redsaumon commented on product/views.py
> +            page_size    = 9
지훈님 page_size변수를 없애고 page_size변수를 넣은 자리를 9로 바꾸면 좋겠다는 말씀이신가요?

2021-01-15 13:59 UTC, redsaumon commented
@ulfrid 지훈님! 문제가 많습니다!

1. 카테고리별 상품 전체보기를 쿼리스트링으로 추가하니 장고쉘에서는 잘 받아지는 값이 vscode에서 작성하면 non-iterable int 오류가 나요.
2. 리스트 컴프리헨션으로 바꿔보라고 하셨던 for문은 안에서 변수를 만들고, 그 변수로 딕셔너리를 만드는데 이것을 어떻게 해야할지 감도 안잡힙니다..!

2021-01-16 11:54 UTC, ulfrid commented
고생하셨습니다 LGTM👍

2021-01-16 11:54 UTC, merged