[16기 홍연우] Add: 상품 상세 보기
wecode-bootcamp-korea/Wepicker-backend pull request #6
Opened 2021-01-17 12:27 UTC by redsaumon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-18 09:45 UTC, ulfrid requested changes

2021-01-18 09:45 UTC, ulfrid commented on product/views.py
> +            product = product_id
필요없는 코드 같습니다.

2021-01-18 09:45 UTC, ulfrid commented on product/views.py
> +            }
이렇게 처리하면 코드가 많이 수동적인것 같아요.
```suggestion
            product = Product.objects.filter(id=product_id).prefetch_related('option', 'image_url')[0]           
            
            product_dict = {
                'product_id'    : product.id,
                'product_name'  : product.name,
                'product_price' : product.price,
                'description'   : product.description,
                'image_list'    : product.image_url.values_list('image_url', flat=True),
                'option_list'   : [
                    {
                        'option_name' : option.name,
                        'option_price' : option.price
                     } for option in product.option.all()
                 ]
            }
```
이렇게 해보면 어떨까요?

2021-01-18 10:22 UTC, redsaumon commented on product/views.py
> +            product = product_id
헉 뭘 하려다 까먹고 뒀네요! 지우겠습니다!

2021-01-18 10:23 UTC, redsaumon commented on product/views.py
> +            }
멋져요!!!!!!:+1:

2021-01-18 11:57 UTC, redsaumon commented on product/views.py
> +            }
지훈님 values_list로 받은 값이 쿼리셋 객체라 json serialize오류가 나길래 for문으로 빼서 넣었어요! 혹시 더 좋은 방법이 있을까요?

2021-01-18 14:08 UTC, ulfrid commented on product/views.py
> +            }
음 아마 저코드에서는 그냥 저 values_list찍는 코드에 [ ]로  감싸줬으면 되지 않았을까 생각됩니다~!

2021-01-18 14:09 UTC, ulfrid commented on product/views.py
> +            }
한번 해보시고 잘되면 이걸로 해서 제출해주세여~!

2021-01-19 00:14 UTC, redsaumon commented on product/views.py
> +            }
제출했습니다~!~!!! :+1:

2021-01-19 00:21 UTC, ulfrid commented
LGTM 👍

2021-01-19 00:22 UTC, merged