[16기 홍연우]Add: 장바구니 담기
wecode-bootcamp-korea/Wepicker-backend pull request #7
Opened 2021-01-19 06:52 UTC by redsaumon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-19 13:50 UTC, ulfrid commented
부분적인 코드의 문제라기보다는 설계에서 조금 더 개선했으면 하는 부분이 있습니다.
1. 장바구니의 생성시 기존 order의 생성 여부를 판단한 생성 및 관리.
2. 장바구니 생성시 같은 상품이 들어올 경우 개수만 증가시키는 로직의 추가 구현
3. 여러개를 수정하는 경우가 있는지, 무조건 개별적 수정하게 되는지에 따른 로직 수정.
일단 이정도 입니다~

2021-01-22 02:48 UTC, ulfrid requested changes

2021-01-22 02:48 UTC, ulfrid commented on order/views.py
> +                    delivery_cost = 2
당장은 어쩔수 없지만, 나중에 꼭 리팩토링 하셨으면 좋겠습니다.

2021-01-22 02:48 UTC, ulfrid commented on order/views.py
> +
JSONField 를 사용하는것에 대한 학습은 좋았지만, 코드적으로는 오히려 비효율적이 됐다고 느끼실 것 같아요.
추후에 모델 변경 및 관계형 데이터로 다시 도전해 보실것을 권유 드립니다.
그리고,  메소드 혹은 클래스를  분할해서 추가시 해야 할 일, 수정시 해야 할 일을 나눠서 작성해보세요.

2021-01-22 02:48 UTC, merged

2021-01-22 11:26 UTC, redsaumon commented on order/views.py
> +
넵!! 리팩토링 기대 중입니다~

2021-01-22 11:27 UTC, redsaumon commented on order/views.py
> +                    delivery_cost = 2
네!!!!!!!!! 프론트에서도 아쉬워하는 부분입니다... 개선사항 1순위..!